"""Central write-classification policy.

`classify_write(path, root, event_type)` is the single source of truth for
"what pipelines should run for this file change?" Every write ingress --
the file watcher, `smriti_write`, `smriti ingest`, direct writer calls --
goes through this function.

Adding a new pipeline means adding one row here, not touching every caller.

The function returns a list of `QueueTask` objects. The caller enqueues
them. Structural-level work that must run synchronously (regenerating
parent `index.md` files) is NOT returned here -- the caller invokes it
directly alongside the classify call. The queue is for async work.

Policy summary (see ~/.narada/.smriti/pipelines.md for full data flow):

    1. Excluded paths (.smriti/, .git/, index.md, non-.md, *.summary.md)
       -> []
    2. Protected trunk files (MEMORY.md, identity.md, mind.md, suti.md, ...)
       -> [wake_summary if identity-file, reindex] only
    3. Large files (>50KB) -> append summarize_pending
    4. Journal daily entries -> append journal_rollup for missing summaries
    5. Leaf-capture paths (sources/, inbox/, heartbeat/artifacts/, ...)
       -> append ingest (consolidate)
    6. Non-leaf content pages -> append route
    7. Identity files (watched by wake_summary) -> append wake_summary
    8. Always append reindex (idempotent; runs last in sleep)
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from smriti.store.cascade import PROTECTED_FILES
from smriti.store.queue import QueueTask
from smriti.store.router import is_leaf_path
from smriti.store.wake_summary import is_identity_file

log = logging.getLogger(__name__)

# Files >= this size get a .summary.md sidecar before any downstream
# pipeline reads them. Applies tree-wide (not just to sources/).
SUMMARIZE_THRESHOLD_BYTES = 50_000

# Pattern matching daily journal entries, e.g. journal/2026/04/week4/04-24.md
_JOURNAL_DAILY_RE = re.compile(
    r"^journal/\d{4}/\d{2}/week\d/\d{2}-\d{2}\.md$"
)
# Rollup summaries at each time level. These are produced by journal_rollup
# itself (narrative compression) and must NOT be fed back into ingest --
# they are already compressed, and consolidating a compressed rollup would
# duplicate the insight extraction over stale aggregates.
_JOURNAL_SUMMARY_RES = (
    re.compile(r"^journal/\d{4}/\d{2}/week\d/week\d\.md$"),   # weekN.md
    re.compile(r"^journal/\d{4}/\d{2}/\d{2}\.md$"),           # MM.md
    re.compile(r"^journal/\d{4}/\d{4}\.md$"),                 # YYYY.md
)


# ── Predicates ──────────────────────────────────────────────────────


def _rel(path: Path, root: Path) -> str | None:
    """Return forward-slash relative path, or None if path is outside root."""
    try:
        return str(path.relative_to(root)).replace("\\", "/")
    except ValueError:
        return None


def _is_excluded(rel: str, path: Path) -> bool:
    """Paths we should never process at all."""
    if rel.startswith(".smriti/") or rel.startswith(".git/"):
        return True
    if path.suffix != ".md":
        return True
    if path.name == "index.md":
        # Generated by structural_cascade; watching it creates a loop.
        return True
    if _is_summary_sidecar(rel):
        # Summaries are derived artifacts; don't re-summarize or re-consolidate.
        return True
    return False


def _is_summary_sidecar(rel: str) -> bool:
    """True for `*.summary.md` files (the output of the summarize pipeline)."""
    return rel.endswith(".summary.md")


def _is_protected(path: Path) -> bool:
    """Trunk file that cascade must not rewrite."""
    return path.name in PROTECTED_FILES


def _is_journal_daily(rel: str) -> bool:
    """True for journal/YYYY/MM/weekN/MM-DD.md."""
    return bool(_JOURNAL_DAILY_RE.match(rel))


def _is_journal_summary(rel: str) -> bool:
    """True for journal rollup summaries (weekN.md, MM.md, YYYY.md)."""
    return any(r.match(rel) for r in _JOURNAL_SUMMARY_RES)


def _is_goal_file(rel: str) -> bool:
    """True for anything under goals/ — protected branch, reindex only."""
    return rel.startswith("goals/")


def _needs_summarize(path: Path, rel: str | None = None) -> bool:
    """True if `path` is >= SUMMARIZE_THRESHOLD_BYTES and sidecar is missing
    or older than the source.

    Mirrors/ is excluded: those paths are junctions into other projects'
    working trees, and writing `.summary.md` sidecars would pollute the
    real project directories via the junction.
    """
    if not path.exists():
        return False
    if rel is not None and rel.startswith("mirrors/"):
        return False
    try:
        size = path.stat().st_size
    except OSError:
        return False
    if size < SUMMARIZE_THRESHOLD_BYTES:
        return False
    sidecar = summary_sidecar_path(path)
    if not sidecar.exists():
        return True
    try:
        return sidecar.stat().st_mtime < path.stat().st_mtime
    except OSError:
        return True


def summary_sidecar_path(path: Path) -> Path:
    """Return the conventional `.summary.md` sidecar path for `path`.

    Example: `foo/bar.md` -> `foo/bar.summary.md`.
    """
    return path.with_suffix(".summary.md")


# ── Journal rollup task generation ──────────────────────────────────


def _journal_rollup_tasks(path: Path, root: Path) -> list[QueueTask]:
    """Generate journal_rollup tasks for any missing week/month/year summary.

    Only emits tasks for summaries that don't already exist -- mirrors the
    behavior of `writer._queue_journal_rollup` that this replaces.
    """
    tasks: list[QueueTask] = []
    try:
        rel = path.relative_to(root)
    except ValueError:
        return tasks

    parts = rel.parts  # ('journal', 'YYYY', 'MM', 'weekN', 'MM-DD.md')
    if len(parts) < 5:
        return tasks

    branch, year, month, week_dir, _daily = parts

    targets = [
        (root / branch / year / month / week_dir / f"{week_dir}.md", 3),
        (root / branch / year / month / f"{month}.md", 2),
        (root / branch / year / f"{year}.md", 1),
    ]

    for summary_path, priority in targets:
        if summary_path.exists():
            continue
        try:
            rel_path = str(summary_path.relative_to(root)).replace("\\", "/")
        except ValueError:
            continue
        tasks.append(
            QueueTask(type="journal_rollup", path=rel_path, priority=priority)
        )

    return tasks


# ── Main entrypoint ─────────────────────────────────────────────────


def classify_write(
    path: Path,
    root: Path,
    event_type: str = "modified",
) -> list[QueueTask]:
    """Return the list of QueueTasks that should be enqueued for this write.

    Parameters
    ----------
    path:
        Absolute path of the file that was written/created/modified/deleted.
    root:
        Tree root.
    event_type:
        One of "created", "modified", "deleted". Deletions return [] --
        structural cascade handles cleanup synchronously.
    """
    if event_type == "deleted":
        return []

    rel = _rel(path, root)
    if rel is None:
        return []

    if _is_excluded(rel, path):
        return []

    tasks: list[QueueTask] = []

    # Always reindex (runs last in sleep; no-op if content unchanged at indexer level).
    reindex_task = QueueTask(type="reindex", path=rel, priority=1)

    # Protected trunk: reindex + wake_summary if applicable. Never enqueue
    # write-back pipelines (summarize/ingest/route/cognitive_cascade).
    if _is_protected(path):
        if is_identity_file(rel):
            tasks.append(QueueTask(type="wake_summary", path=rel, priority=3))
        tasks.append(reindex_task)
        return tasks

    # Goals branch: treated as protected at branch level.
    if _is_goal_file(rel):
        tasks.append(reindex_task)
        return tasks

    # Size gate: large files get summarized before downstream pipelines
    # consume them. Sidecar is the thing consolidate/search prefers.
    if _needs_summarize(path, rel):
        tasks.append(QueueTask(type="summarize_pending", path=rel, priority=4))

    # Journal daily entries -> rollup (only for missing summaries).
    if _is_journal_daily(rel):
        tasks.extend(_journal_rollup_tasks(path, root))

    # Leaf captures (sources/, inbox/, heartbeat/artifacts/, journal dailies, ...)
    # -> consolidate. Exception: journal rollup summaries are already
    # compressed narrative; they should not be fed back into ingest.
    if is_leaf_path(rel):
        if _is_journal_summary(rel):
            # Rollup summary: reindex only, no consolidation.
            pass
        else:
            tasks.append(QueueTask(type="ingest", path=rel, priority=5))
    else:
        # Non-leaf content page -> routing judge looks for cross-links.
        tasks.append(QueueTask(type="route", path=rel, priority=5))

    # Identity file change -> rebuild wake context.
    if is_identity_file(rel):
        tasks.append(QueueTask(type="wake_summary", path=rel, priority=3))

    tasks.append(reindex_task)
    return tasks
